### ISSUE TITLE
figur og tabell-titler er på engelsk og uten kapittelnummerering

### ISSUE THREAD

**Issue by sda030** [NIFU-NO/nifutypst#18]
![image](https://github.com/NIFU-NO/nifutypst/assets/13221371/465348b6-4392-4fdc-aa57-beea8b2f3bc1)

**Comment by sda030** [comment]
Kapittelnummerering: https://typst.app/docs/roadmap/
"Relative counters, e.g. for figure numbering per section"

**Comment by henrikkarlstrom** [comment]
For at Quarto ikke skal overkjøre alt på veien fra .qmd via pandoc til .typ må lokaliseringen av tabell- og figurtitler gjøres i YAML-blokka i .qmd-fila, som dette:

```
crossref:
  custom:
    - kind: float
      reference-prefix: Figur
      key: fig
    - kind: float
      reference-prefix: Tabell
      key: tbl
```

Da får vi:

![bilde](https://github.com/NIFU-NO/nifutypst/assets/35686798/1170c945-89aa-4f64-8d4f-ac50054e6d3d)

Så jeg anser dette problemet for løst.

Kapittelnummerering må jeg tygge litt på. Det skal nok la seg gjøre å hacke til noe p.t., men om det er like rundt hjørnet på veikartet til Typst er det mye bedre å la dem implementere det på skikkelig vis.
